---
- name: Installing andrewrothstein.epel
  ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: OS pkg install..
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ mosh_os_pkgs | default(["mosh"]) }}'
    state: present
