---
- ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: os pkg install..
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ mosh_os_pkgs | default(["mosh"]) }}'
    state: present
